---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: streamblu
  name: streamblu
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: grpc_node_mapping
      grpc: True
      prefix: /datastream.GRPCDataStream/
      rewrite: /datastream.GRPCDataStream/
      service: streamblu
spec:
  type: ClusterIP
  ports:
  - name: streamblu
    port: 80
    targetPort: grpc-api
  selector:
    service: streamblu
