---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: streamblu
  name: streamblu
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: grpc_node_mapping
      grpc: True
      prefix: /datastreamblu.GRPCDataStreamBLU/
      rewrite: /datastreamblu.GRPCDataStreamBLU/
      service: streamblu
spec:
  type: ClusterIP
  ports:
  - name: grpc-node-stream
    port: 80
    targetPort: grpc-node-api
  selector:
    service: streamblu
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamblu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: streamblu
    spec:
      containers:
      - name: streamblu
        image: arunramakani/stream-blu
        env:
        - name: MY_SQL
          value: mysql
        ports:
        - name: grpc-node-api
          containerPort: 50051
      restartPolicy: Always
